/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>			// File Control Definitions.
#include <termios.h>		// POSIX Terminal Control Definitions.
#include <unistd.h>			// UNIX Standard Definitions.
#include <errno.h>			// ERROR Number Definitions.
#include <pthread.h>
#include <sys/select.h>
#include <sys/time.h>
#include <signal.h>
#include <time.h>
#include <assert.h>
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char findTheDifference(char * s, char * t){
    int slen = (int)strlen(s);
    int tlen = (int)strlen(t);

    char ans = 0;
    for(int i = 0;i<slen;i++){
        ans ^=s[i];
        ans ^=t[i]; 
    }
    ans ^=t[tlen-1];
    return ans;
#if 0
    int sval = 0;
    int tval = 0;
    printf("%d %d\n",slen,tlen);
    for(int i = 0;i<slen;i++){
        int idx = s[i] - 'a';
        sval = sval|(1<<idx);
    }
    for(int i = 0;i<tlen;i++){
        int idx = t[i] - 'a';
        tval = tval|(1<<idx);
    }
    int diffval = sval^tval;
    printf("%d %d diff idx = %d\n",sval,tval,diffval);
    int pos = 0;
    while(diffval){
        if(diffval&1)
            break;
        pos++;
        diffval = diffval>>1;
    }
    
    return 'a'+pos;
#endif    
}

int main(int argc, char** argv)
{
    //int num = atoi(argv[1]);

    char *sstring="abcd";
    char *tstring="abcdt";
    printf("%s,%s\n",sstring,tstring);
    char res = findTheDifference(sstring,tstring);
    printf("res =%d\n",res);
    return 0;
}

